services:
  db:
    image: postgres:16
    container_name: log-db
    environment:
      POSTGRES_USER: sergo_user
      POSTGRES_PASSWORD: 13410285
      POSTGRES_DB: log-analyzer
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: log-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
